### ISSUE TITLE
Cmake fail

### ISSUE THREAD

**Issue by SimiPro** [eth-igl/GP2019-Assignments#1]
On my machine: Ubuntu 18.04  cmake fails because of this 2 lines in the CMakeLists.txt: 
`add_executable(${PROJECT_NAME} ${SRCFILES})`
`target_link_libraries(${PROJECT_NAME}_bin igl::core igl::opengl_glfw)`
So on my system the executable gets built without the _bin. By removing the _bin from the 2nd line it works fine. I do not know if this is intentional.

**Comment by oliglauser** [comment]
Thanks for pointing out. You are too fast for us ;)
